### ISSUE TITLE
Error: Not enough balance

### ISSUE THREAD

**Issue by masonwilliams6** [Savjee/SavjeeCoin#37]
```
Error: Not enough balance
    at Blockchain.addTransaction (/Users/mwill/Documents/GitHub/SavjeeCoin/src/blockchain.js:196:13)
    at Object.<anonymous> (/Users/mwill/Documents/GitHub/SavjeeCoin/src/main.js:17:12)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
mwill@Masons-Air SavjeeCoin % 
```

**Comment by masonwilliams6** [comment]
#38

**Comment by Savjee** [comment]
Thanks! Merged in!
